# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Numerical Cosmology Library
name: NumCosmo
email: sandro@isoftware.com.br
#location: My location # ex. Nice, France
#company: MyCompany
#company_url: my_company_website
github_url: https://github.com/NumCosmo
description: NumCosmo website
favicon: favicon.png # Image must be in assets/images
repository: numcosmo/numcosmo.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://numcosmo.github.io/

## Gem
plugins:
  - jekyll-paginate
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  highlighter: rouge
  

# Permalinks
permalink:   pretty
baseurl:     /

# Disque
disque: numcosmo.disqus.com

# Pagination
paginate: 5
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /about
    label: About

  -
    href: /news
    label: News

  -
    href: /download
    label: Installation

  -
    href: /tutorials
    label: Tutorials

  -
    href: /examples
    label: Examples

  -
    href: /manual
    label: Manual




# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-36056599-1'

# NumCosmo version

version: 0.13.3
