project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - install.qmd
    - manual.qmd

website:
  title: "The Numerical Cosmology Library"
  favicon: favicon_numcosmo.png
  navbar:
    search: true
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/NumCosmo/NumCosmo
          - text: "Issues"
            href: https://github.com/NumCosmo/NumCosmo/issues
    left:
      - about.qmd
      - install.qmd
      - text: "Manual"
        href: manual.qmd
  sidebar:
      style: "docked"
      logo: numcosmo_logo.png
      contents:
        - section: "Basics"
          contents:
            - href: about.qmd
              text: "Introduction"

resources:
  - manual/**

format:
  html:
    theme: [serif, custom.scss]
    toc: true
    code-overflow: wrap
    grid:
      body-width: 1200px

reference-location: margin
citation-location: margin
authors:
  - NumCosmo developers
jupyter: python3
version: 0.22.0
