on:
  workflow_dispatch:
  push:
      branches: master
  schedule:
    - cron: '0 12 * * SUN'
  
name: NumCosmo Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: actions/checkout@v3
      - name: Setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: numcosmo
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          show-channel-urls: true
          use-mamba: true
          conda-remove-defaults: true
          miniforge-version: latest
      - name: Create environment
        run: mamba create -v -q -n numcosmo numcosmo jupyter nbformat pandas plotnine "getdist>=1.5.1"
      - name: Activate Conda Environment
        run: conda activate numcosmo
      - name: Quarto Render
        run: quarto render
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
